[package]
name = "golrev"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
num-bigint = "0.4.6"
num-traits = "0.2.19"
rand = "0.8.5"
rayon = "1.10.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
